name: Release Changelog Bot

on:
  push:
    tags:
      - "v*"

jobs:
  changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Get Last Commits
        id: commits
        run: |
          echo "::set-output name=list::$(git log -n 10 --pretty=format:'- %s' | jq -Rs .)"

      - name: Ask GPT for Changelog
        id: gpt
        run: |
          echo "${{ steps.commits.outputs.list }}" > commitlist.txt
          curl https://api.openai.com/v1/chat/completions \
            -H "Authorization: Bearer ${{ secrets.OPENAI_API_KEY }}" \
            -H "Content-Type: application/json" \
            -d '{
              "model": "gpt-4",
              "messages": [
                { "role": "system", "content": "Create a concise changelog from these commits." },
                { "role": "user", "content": '"$(cat commitlist.txt | jq -Rs .)"' }
              ]
            }' > gpt_output.json
          echo "::set-output name=summary::$(jq -r .choices[0].message.content gpt_output.json)"

      - name: Comment on Release PR (if applicable)
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_URL=$(gh pr list --state open --search "release" --json url -q '.[0].url')
          if [ -n "$PR_URL" ]; then
            gh pr comment "$PR_URL" --body "📝 **Changelog (Auto-generated)**\n\n${{ steps.gpt.outputs.summary }}"
          fi
        continue-on-error: true
